function scopedOrders(){
  let arr=getFilteredOrders(true);if(state.orderScope==='active')arr=arr.filter(o=>!o.archived);if(state.orderScope==='archived')arr=arr.filter(o=>o.archived);
  const dir=state.sort.dir==='asc'?1:-1;return arr.sort((a,b)=>compareValues(sortValue(a,state.sort.key),sortValue(b,state.sort.key))*dir);
}
function sortValue(o,key){if(key==='age')return ageDays(o);return o[key]??''}
function compareValues(a,b){if(typeof a==='number'&&typeof b==='number')return a-b;return String(a).localeCompare(String(b),'es',{numeric:true})}
function sortOrders(key){if(state.sort.key===key)state.sort.dir=state.sort.dir==='asc'?'desc':'asc';else state.sort={key,dir:'asc'};renderOrders()}
function renderOrders(){
  const arr=scopedOrders();const pages=Math.max(1,Math.ceil(arr.length/state.pageSize));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.pageSize;const rows=arr.slice(start,start+state.pageSize);
  $('ordersCount').textContent=`${arr.length} registros`;$('pageInfo').textContent=`Página ${state.page} de ${pages}`;$('prevPageBtn').disabled=state.page<=1;$('nextPageBtn').disabled=state.page>=pages;
  $('ordersTable').querySelector('tbody').innerHTML=rows.map(orderRow).join('');$('ordersCards').innerHTML=rows.map(orderCard).join('');
  $$('[data-select-order]').forEach(c=>{c.checked=state.selected.has(c.dataset.selectOrder);c.onchange=()=>toggleOrderSelection(c.dataset.selectOrder,c.checked)});
  $$('[data-view-order]').forEach(b=>b.onclick=()=>openOrderDetail(b.dataset.viewOrder));$$('[data-edit-order]').forEach(b=>b.onclick=()=>openOtForm(b.dataset.editOrder));$$('[data-archive-order]').forEach(b=>b.onclick=()=>archiveOrder(b.dataset.archiveOrder));
  updateSelectionUI();
}
function orderRow(o){return `<tr><td><input type="checkbox" data-select-order="${o.id}" aria-label="Seleccionar OT ${esc(o.ot)}"></td><td class="nowrap"><strong>${esc(o.ot)}</strong></td><td class="nowrap">${fmtDate(o.date)}</td><td>${esc(o.sector)}</td><td><strong>${esc(o.equipment)}</strong><br><span class="muted">${esc(o.assetCode||'')}</span></td><td class="cell-description">${esc(o.description)}</td><td>${badge(o.type)}</td><td>${badge(o.criticality)}</td><td>${badge(o.status)}</td><td>${esc(o.supervisor||'—')}</td><td>${esc(o.executor||'—')}</td><td class="nowrap">${ageDays(o)} d${isOverdue(o)?' ⚠':''}</td><td><div class="row-actions"><button data-view-order="${o.id}" title="Ver">👁</button><button data-edit-order="${o.id}" title="Editar" ${canEdit()?'':'disabled'}>✎</button><button data-archive-order="${o.id}" title="${o.archived?'Restaurar':'Archivar'}" ${canArchive()?'':'disabled'}>${o.archived?'↥':'⌫'}</button></div></td></tr>`}
function orderCard(o){return `<article class="mobile-order-card"><div class="mobile-card-top"><div><h3>OT ${esc(o.ot)} · ${esc(o.equipment)}</h3><p>${fmtDate(o.date)} · ${esc(o.sector)}</p></div><input type="checkbox" data-select-order="${o.id}"></div><div class="mobile-description">${esc(o.description)}</div><div class="mobile-tags">${badge(o.status)}${badge(o.type)}${badge(o.criticality)}<span class="badge badge-gray">${ageDays(o)} días</span></div><div class="mobile-actions"><button class="btn secondary compact" data-view-order="${o.id}">Ver</button><button class="btn primary compact" data-edit-order="${o.id}" ${canEdit()?'':'disabled'}>Editar</button></div></article>`}
function badge(v){const x=norm(v);let cls='badge-gray';if(['A','PENDIENTE','CORRECTIVO'].includes(x))cls='badge-red';else if(['FINALIZADO','CERRADO','COMPLETADO','PREVENTIVO','B'].includes(x))cls='badge-green';else if(['PROGRAMADO','MEJORA','C'].includes(x))cls='badge-blue';else if(['EN COMPRA','EN PROCESO'].includes(x))cls='badge-orange';else if(['STAND BY','PAUSADO'].includes(x))cls='badge-purple';return `<span class="badge ${cls}">${esc(v||'Sin dato')}</span>`}
function toggleOrderSelection(id,checked){checked?state.selected.add(id):state.selected.delete(id);updateSelectionUI()}
function toggleSelectAll(){const checked=$('selectAllOrders').checked;scopedOrders().forEach(o=>checked?state.selected.add(o.id):state.selected.delete(o.id));renderOrders()}
function updateSelectionUI(){$('selectedCount').textContent=`${state.selected.size} seleccionadas`;$('bulkStatusBtn').disabled=!state.selected.size||!canEdit();$('bulkArchiveBtn').disabled=!state.selected.size||!canArchive();}

function canCreate(){return !['Solo lectura'].includes(state.settings.role)}function canEdit(){return !['Solo lectura'].includes(state.settings.role)}function canArchive(){return state.settings.role==='Administrador'}function canImport(){return ['Administrador','Supervisor'].includes(state.settings.role)}
function applyRolePermissions(){
  ['newOtBtn','ordersNewBtn','mobileNewBtn'].forEach(id=>$(id).disabled=!canCreate());$('importInput').closest('label').style.opacity=canImport()?'1':'.45';$('importInput').disabled=!canImport();$('clearDataBtn').disabled=!canArchive();
}
function applySettingsToUI(){
  $('currentUserName').textContent=state.settings.userName;$('currentRole').textContent=state.settings.role;$('userInitials').textContent=state.settings.userName.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
  $('settingsUserName').value=state.settings.userName;$('settingsRole').value=state.settings.role;$('catalogStatuses').value=state.settings.statuses.join(', ');$('catalogTypes').value=state.settings.types.join(', ');$('catalogCriticalities').value=state.settings.criticalities.join(', ');applyRolePermissions();
}
function renderSettings(){applySettingsToUI()}
async function saveUserSettings(){state.settings.userName=$('settingsUserName').value.trim()||'Usuario local';state.settings.role=$('settingsRole').value;await idbPut('settings',state.settings);applySettingsToUI();await audit('CONFIGURACION',null,`Usuario local actualizado: ${state.settings.userName} (${state.settings.role}).`);toast('Usuario y rol actualizados.','success')}
async function saveCatalogs(){
  const parse=id=>unique($(id).value.split(',').map(norm));state.settings.statuses=parse('catalogStatuses');state.settings.types=parse('catalogTypes');state.settings.criticalities=parse('catalogCriticalities');await idbPut('settings',state.settings);populateFilterOptions();await audit('CONFIGURACION',null,'Se actualizaron los catálogos de estado, tipo y criticidad.');toast('Catálogos guardados.','success')
}

function openOtForm(id=null){
  if(!canEdit()){toast('El rol actual es de solo lectura.','error');return}
  state.editingId=id;state.pendingAttachments=[];const o=id?state.orders.find(x=>x.id===id):null;$('otForm').reset();populateOrderSelects();$('otId').value=id||'';
  $('otDialogTitle').textContent=o?'Editar orden de trabajo':'Nueva orden de trabajo';$('otDialogSubtitle').textContent=o?`OT ${o.ot} · última actualización ${fmtDateTime(o.updatedAt)}`:'Complete los datos principales.';
  $('otNumber').value=o?.ot||nextOtNumber();$('otDate').value=o?.date||todayISO();$('otDueDate').value=o?.dueDate||'';$('otSector').value=o?.sector||'';$('otEquipment').value=o?.equipment||'';$('otAssetCode').value=o?.assetCode||'';$('otRequester').value=o?.requester||state.settings.userName;
  $('otType').value=o?.type||state.settings.types[0];$('otCriticality').value=o?.criticality||state.settings.criticalities[1]||state.settings.criticalities[0];$('otStatus').value=o?.status||state.settings.statuses[0];$('otSupervisor').value=o?.supervisor||'';$('otExecutor').value=o?.executor||'';$('otPlannedHours').value=o?.plannedHours??'';$('otActualHours').value=o?.actualHours??'';$('otCompletionDate').value=o?.completionDate||'';$('otDescription').value=o?.description||'';$('otComments').value=o?.comments||'';
  state.pendingAttachments=o?.attachments?[...o.attachments]:[];renderAttachmentPreview();$('otDialog').showModal();
}
function nextOtNumber(){const nums=state.orders.map(o=>String(o.ot).trim()).filter(v=>/^\d+$/.test(v)).map(Number).filter(Number.isFinite);return String((Math.max(0,...nums)||0)+1)}
async function handleAttachments(e){
  const files=[...e.target.files];for(const file of files){if(file.size>2.5*1024*1024){toast(`${file.name}: supera 2,5 MB.`, 'error');continue}const data=await fileToDataURL(file);state.pendingAttachments.push({id:uid(),name:file.name,type:file.type,size:file.size,data});}renderAttachmentPreview();e.target.value='';
}
function fileToDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file)})}
function renderAttachmentPreview(){$('attachmentPreview').innerHTML=state.pendingAttachments.map(a=>`<div class="attachment-item">${a.type?.startsWith('image/')?`<img src="${a.data}" alt="">`:'<span>📎</span>'}<span>${esc(a.name)}<br><small>${fmtNumber(a.size/1024,0)} KB</small></span><button type="button" data-remove-attachment="${a.id}">✕</button></div>`).join('');$$('[data-remove-attachment]').forEach(b=>b.onclick=()=>{state.pendingAttachments=state.pendingAttachments.filter(a=>a.id!==b.dataset.removeAttachment);renderAttachmentPreview()})}
async function saveOrderFromForm(e){
  e.preventDefault();const old=state.editingId?state.orders.find(o=>o.id===state.editingId):null;const now=new Date().toISOString();const status=norm($('otStatus').value);let completion=$('otCompletionDate').value;if(CLOSED_STATUSES.includes(status)&&!completion)completion=todayISO();
  const o={id:old?.id||uid(),ot:$('otNumber').value.trim(),date:$('otDate').value,dueDate:$('otDueDate').value,sector:$('otSector').value.trim(),equipment:$('otEquipment').value.trim(),assetCode:$('otAssetCode').value.trim(),requester:normalizePerson($('otRequester').value),type:norm($('otType').value),criticality:norm($('otCriticality').value),status,supervisor:normalizePerson($('otSupervisor').value),executor:normalizePerson($('otExecutor').value),plannedHours:toNumber($('otPlannedHours').value),actualHours:toNumber($('otActualHours').value),completionDate:completion,description:$('otDescription').value.trim(),comments:$('otComments').value.trim(),attachments:state.pendingAttachments,archived:old?.archived||false,createdAt:old?.createdAt||now,updatedAt:now};
  if(!o.ot||!o.date||!o.sector||!o.equipment||!o.description){toast('Complete los campos obligatorios.','error');return}
  const duplicate=state.orders.find(x=>x.id!==o.id&&norm(x.ot)===norm(o.ot));if(duplicate&&!confirm(`La OT ${o.ot} ya existe. ¿Guardar de todas formas?`))return;
  await idbPut('orders',o);if(old){state.orders=state.orders.map(x=>x.id===o.id?o:x);const changes=diffOrders(old,o);await audit('EDICION',o,changes.length?`Campos modificados: ${changes.join(', ')}.`:'Se guardó la orden sin cambios visibles.')}else{state.orders.push(o);await audit('ALTA',o,`Se creó la OT ${o.ot} para ${o.equipment}.`)}
  $('otDialog').close();toast(`OT ${o.ot} guardada.`, 'success');await refreshAll();
}
function diffOrders(a,b){const labels={ot:'número',date:'fecha',dueDate:'fecha objetivo',sector:'sector',equipment:'equipo',assetCode:'código de activo',requester:'solicitante',type:'tipo',criticality:'criticidad',status:'estado',supervisor:'supervisor',executor:'ejecutor',plannedHours:'horas planificadas',actualHours:'horas reales',completionDate:'fecha de finalización',description:'descripción',comments:'comentarios'};return Object.keys(labels).filter(k=>String(a[k]??'')!==String(b[k]??'')).map(k=>labels[k])}

function openOrderDetail(id){
  $('detailEditBtn').style.display='';
  const o=state.orders.find(x=>x.id===id);if(!o)return;state.detailId=id;$('detailTitle').textContent=`OT ${o.ot} · ${o.equipment}`;$('detailSubtitle').textContent=`${o.sector} · ${fmtDate(o.date)} · ${o.status}`;
  const attachments=(o.attachments||[]).map(a=>`<a class="attachment-item" href="${a.data}" download="${esc(a.name)}">${a.type?.startsWith('image/')?`<img src="${a.data}" alt="">`:'📎'}<span>${esc(a.name)}</span></a>`).join('')||'<span class="muted">Sin archivos adjuntos.</span>';
  const hist=state.audit.filter(a=>a.orderId===o.id).slice(0,20).map(a=>`<div class="audit-item"><div class="audit-time">${fmtDateTime(a.ts)}</div><div class="audit-line"><div class="audit-dot"></div></div><div class="audit-content"><strong>${esc(a.action)}</strong><p>${esc(a.details)}</p></div></div>`).join('')||'<p class="muted">Sin historial disponible.</p>';
  $('detailBody').innerHTML=`<div class="detail-grid">${detailBox('Estado',badge(o.status))}${detailBox('Criticidad',badge(o.criticality))}${detailBox('Tipo',badge(o.type))}${detailBox('Antigüedad',`${ageDays(o)} días`)}${detailBox('Fecha objetivo',fmtDate(o.dueDate))}${detailBox('Finalización',fmtDate(o.completionDate))}${detailBox('Horas plan.',`${fmtNumber(o.plannedHours,1)} h`)}${detailBox('Horas reales',`${fmtNumber(o.actualHours,1)} h`)}</div><div class="detail-section"><h3>Descripción</h3><div class="detail-text">${esc(o.description)}</div></div><div class="detail-section"><h3>Responsables</h3><div class="detail-grid">${detailBox('Solicitante',esc(o.requester||'—'))}${detailBox('Supervisor',esc(o.supervisor||'—'))}${detailBox('Ejecutor',esc(o.executor||'—'))}${detailBox('Código de activo',esc(o.assetCode||'—'))}</div></div><div class="detail-section"><h3>Comentarios</h3><div class="detail-text">${esc(o.comments||'Sin comentarios.')}</div></div><div class="detail-section"><h3>Evidencias</h3><div class="attachment-preview">${attachments}</div></div><div class="detail-section"><h3>Historial de la OT</h3>${hist}</div>`;
  $('detailEditBtn').disabled=!canEdit();$('detailDialog').showModal();
}
function detailBox(label,value){return `<div class="detail-box"><small>${label}</small><strong>${value}</strong></div>`}
async function archiveOrder(id){if(!canArchive())return;const o=state.orders.find(x=>x.id===id);if(!o)return;o.archived=!o.archived;o.updatedAt=new Date().toISOString();await idbPut('orders',o);await audit(o.archived?'BAJA':'RESTAURACION',o,o.archived?'La orden fue archivada.':'La orden fue restaurada.');toast(o.archived?'OT archivada.':'OT restaurada.','success');refreshAll()}
function openBulkStatus(){if(!state.selected.size)return;$('bulkStatusComment').value='';populateOrderSelects();$('statusDialog').showModal()}
async function applyBulkStatus(e){e.preventDefault();const status=norm($('bulkNewStatus').value),comment=$('bulkStatusComment').value.trim();for(const id of state.selected){const o=state.orders.find(x=>x.id===id);if(!o)continue;const old=o.status;o.status=status;o.updatedAt=new Date().toISOString();if(CLOSED_STATUSES.includes(status)&&!o.completionDate)o.completionDate=todayISO();await idbPut('orders',o);await audit('CAMBIO_ESTADO',o,`${old} → ${status}${comment?`. ${comment}`:''}`)}state.selected.clear();$('statusDialog').close();toast('Estados actualizados.','success');refreshAll()}
async function bulkArchive(){if(!canArchive()||!state.selected.size)return;if(!confirm(`¿Archivar ${state.selected.size} órdenes seleccionadas?`))return;for(const id of state.selected){const o=state.orders.find(x=>x.id===id);if(!o)continue;o.archived=true;o.updatedAt=new Date().toISOString();await idbPut('orders',o);await audit('BAJA',o,'La orden fue archivada mediante acción masiva.')}state.selected.clear();toast('Órdenes archivadas.','success');refreshAll()}
