function renderAssets(){
  const groups=new Map();state.filtered.forEach(o=>{const k=o.equipment||'Sin equipo';if(!groups.has(k))groups.set(k,[]);groups.get(k).push(o)});const data=[...groups.entries()].map(([name,orders])=>({name,orders,open:orders.filter(o=>!isClosed(o)).length,corrective:orders.filter(o=>norm(o.type)==='CORRECTIVO').length,mttr:mttr(orders),mtbf:mtbf(orders),avail:availabilityEstimate(orders),sector:orders[0]?.sector||''})).sort((a,b)=>b.corrective-a.corrective||b.orders.length-a.orders.length);
  $('assetCards').innerHTML=data.length?data.map(a=>`<article class="asset-card" data-asset="${esc(a.name)}"><h3>${esc(a.name)}</h3><p>${esc(a.sector)} · ${a.orders.length} OT registradas</p><div class="asset-metrics"><div class="mini-metric"><strong>${a.open}</strong><small>Abiertas</small></div><div class="mini-metric"><strong>${a.corrective}</strong><small>Correctivos</small></div><div class="mini-metric"><strong>${fmtNumber(a.mttr,1)}d</strong><small>MTTR</small></div><div class="mini-metric"><strong>${fmtNumber(a.mtbf,0)}d</strong><small>MTBF</small></div></div></article>`).join(''):'<article class="panel"><p class="muted">No hay equipos para los filtros actuales.</p></article>';
  $$('[data-asset]').forEach(c=>c.onclick=()=>openAssetDetail(c.dataset.asset));
}
function openAssetDetail(name){
  const orders=state.filtered.filter(o=>o.equipment===name).sort((a,b)=>b.date.localeCompare(a.date));const open=orders.filter(o=>!isClosed(o)).length;state.detailId=null;$('detailTitle').textContent=name;$('detailSubtitle').textContent=`${orders[0]?.sector||''} · historial del activo`;$('detailEditBtn').style.display='none';
  const rows=orders.map(o=>`<tr><td>${esc(o.ot)}</td><td>${fmtDate(o.date)}</td><td>${badge(o.type)}</td><td>${badge(o.status)}</td><td>${ageDays(o)} d</td><td>${fmtNumber(o.actualHours,1)} h</td><td><button class="btn secondary compact" data-view-order="${o.id}">Ver</button></td></tr>`).join('');
  $('detailBody').innerHTML=`<div class="detail-grid">${detailBox('Total OT',orders.length)}${detailBox('Abiertas',open)}${detailBox('Correctivos',orders.filter(o=>norm(o.type)==='CORRECTIVO').length)}${detailBox('MTTR',`${fmtNumber(mttr(orders),1)} días`)}${detailBox('MTBF',`${fmtNumber(mtbf(orders),0)} días`)}${detailBox('Disponibilidad est.',`${fmtNumber(availabilityEstimate(orders),2)}%`)}${detailBox('Horas acumuladas',`${fmtNumber(orders.reduce((s,o)=>s+(Number(o.actualHours)||0),0),1)} h`)}${detailBox('Reincidencia',orders.filter(o=>norm(o.type)==='CORRECTIVO').length>=2?'Sí':'No')}</div><div class="detail-section"><h3>Historial de órdenes</h3><div class="simple-table-wrap"><table><thead><tr><th>OT</th><th>Fecha</th><th>Tipo</th><th>Estado</th><th>Duración</th><th>Horas</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></div>`;
  $$('[data-view-order]',$('detailBody')).forEach(b=>b.onclick=()=>{$('detailDialog').close();$('detailEditBtn').style.display='';openOrderDetail(b.dataset.viewOrder)});$('detailDialog').showModal();
}

function renderPeople(){
  $('executorTableWrap').innerHTML=peopleTable(groupPeople(state.filtered,'executor'),'Ejecutor');$('supervisorTableWrap').innerHTML=peopleTable(groupPeople(state.filtered,'supervisor'),'Supervisor');
}
function groupPeople(orders,key){const m=new Map();orders.forEach(o=>{const n=normalizePerson(o[key])||'Sin asignar';if(!m.has(n))m.set(n,[]);m.get(n).push(o)});return [...m.entries()].map(([name,os])=>({name,total:os.length,closed:os.filter(isClosed).length,open:os.filter(o=>!isClosed(o)).length,hours:os.reduce((s,o)=>s+(Number(o.actualHours)||0),0),rate:os.length?os.filter(isClosed).length/os.length*100:0})).sort((a,b)=>b.total-a.total)}
function peopleTable(data,label){return `<table><thead><tr><th>${label}</th><th>OT</th><th>Abiertas</th><th>Finalizadas</th><th>Horas</th><th>% cierre</th></tr></thead><tbody>${data.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${p.total}</td><td>${p.open}</td><td>${p.closed}</td><td>${fmtNumber(p.hours,1)}</td><td>${fmtNumber(p.rate,1)}%</td></tr>`).join('')}</tbody></table>`}

function renderAudit(){
  const a=state.audit.slice(0,500);$('auditTimeline').innerHTML=a.length?a.map(x=>`<div class="audit-item"><div class="audit-time">${fmtDateTime(x.ts)}</div><div class="audit-line"><div class="audit-dot"></div></div><div class="audit-content"><strong>${esc(x.action)}${x.ot?` · OT ${esc(x.ot)}`:''}</strong><p>${esc(x.details)}</p><div class="audit-tags"><span class="badge badge-gray">${esc(x.user)}</span><span class="badge badge-blue">${esc(x.role)}</span></div></div></div>`).join(''):'<p class="muted">Todavía no hay movimientos registrados.</p>';
}
function exportAudit(){const rows=state.audit.map(a=>({Fecha:a.ts,Accion:a.action,OT:a.ot,Usuario:a.user,Rol:a.role,Detalle:a.details}));exportRows(rows,`historial_ot_mtto_${todayISO()}`)}

function findSheet(workbook){const scored=workbook.SheetNames.map(name=>{const rows=XLSX.utils.sheet_to_json(workbook.Sheets[name],{header:1,defval:''});return {name,rows,score:rows.slice(0,10).reduce((m,r)=>Math.max(m,r.filter(Boolean).length),0)}}).sort((a,b)=>b.score-a.score);return scored[0]}
function cleanHeader(v){return norm(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Z0-9#]+/g,' ').trim()}
const aliases={ot:['OT','#','NUMERO OT','NRO OT','ORDEN','ORDEN DE TRABAJO'],date:['FECHA DE AVISO','FECHA','DIA','FECHA AVISO'],dueDate:['FECHA OBJETIVO','FECHA PROGRAMADA','VENCIMIENTO'],sector:['SALA SECTOR','SECTOR','SALA','AREA'],equipment:['EQUIPO','MAQUINA','ACTIVO'],assetCode:['COD','CODIGO ACTIVO','CODIGO DE ACTIVO'],requester:['SOLICITANTE','PEDIDO POR'],type:['TIPO DE SOLICITUD','TIPO','TIPO OT'],description:['AVISO SOLICITUD','DESCRIPCION','TAREA','DETALLE'],criticality:['CRITICIDAD','PRIORIDAD'],status:['ESTADO','STATUS'],supervisor:['SUPERVISOR','RESPONSABLE'],executor:['EJECUTOR','TECNICO','REALIZADO POR'],plannedHours:['HORAS PLANIFICADAS','HS PLANIFICADAS','TIEMPO PLANIFICADO'],actualHours:['HORAS','HORAS REALES','HS REALES','TIEMPO'],completionDate:['FECHA DE FINALIZACION','FECHA FINALIZACION','FECHA CIERRE'],comments:['OBS','OBSERVACIONES','COMENTARIOS']};
function headerIndex(headers,keys){const candidates=aliases[key].map(cleanHeader);return headers.findIndex(h=>candidates.includes(cleanHeader(h)))}
function parseDateValue(v){
  if(!v)return '';if(v instanceof Date&&!Number.isNaN(v))return v.toISOString().slice(0,10);if(typeof v==='number'&&v>20000&&typeof XLSX!=='undefined'){const p=XLSX.SSF.parse_date_code(v);if(p)return `${p.y}-${String(p.m).padStart(2,'0')}-${String(p.d).padStart(2,'0')}`}
  const s=String(v).trim();const iso=s.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})/);if(iso)return `${iso[1]}-${iso[2].padStart(2,'0')}-${iso[3].padStart(2,'0')}`;const ar=s.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{2,4})/);if(ar){let y=ar[3];if(y.length===2)y=`20${y}`;return `${y}-${ar[2].padStart(2,'0')}-${ar[1].padStart(2,'0')}`}const d=new Date(s);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10);
}
async function importFile(file){
  if(!file)return;if(!canImport()){toast('El rol actual no permite importar.','error');return}try{if(typeof XLSX==='undefined')throw new Error('No se cargó el lector de Excel');const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:true});const sheet=findSheet(wb);if(!sheet||!sheet.rows.length)throw new Error('No se encontraron datos');
    let headerRow=0,best=-1;for(let i=0;i<Math.min(20,sheet.rows.length);i++){const score=sheet.rows[i].filter(v=>Object.values(aliases).flat().map(cleanHeader).includes(cleanHeader(v))).length;if(score>best){best=score;headerRow=i}}const headers=sheet.rows[headerRow];const idx={};Object.keys(aliases).forEach(k=>idx[k]=headerIndex(headers,k));if(idx.description<0||idx.sector<0||idx.equipment<0)throw new Error('No se reconocieron las columnas mínimas: Sector, Equipo y Descripción.');
    const imported=[];for(const row of sheet.rows.slice(headerRow+1)){if(!row.some(Boolean))continue;const val=k=>idx[k]>=0?row[idx[k]]:'';const description=String(val('description')||'').trim();if(!description)continue;const ot=String(val('ot')||nextImportOt(imported)).trim();const old=state.orders.find(o=>norm(o.ot)===norm(ot));const now=new Date().toISOString();imported.push({id:old?.id||uid(),ot,date:parseDateValue(val('date'))||todayISO(),dueDate:parseDateValue(val('dueDate')),sector:String(val('sector')||'Sin sector').trim(),equipment:String(val('equipment')||'Sin equipo').trim(),assetCode:String(val('assetCode')||'').trim(),requester:normalizePerson(val('requester')),type:norm(val('type')||'CORRECTIVO'),description,criticality:norm(val('criticality')||'C'),status:norm(val('status')||'PENDIENTE'),supervisor:normalizePerson(val('supervisor')),executor:normalizePerson(val('executor')),plannedHours:toNumber(val('plannedHours')),actualHours:toNumber(val('actualHours')),completionDate:parseDateValue(val('completionDate')),comments:String(val('comments')||'').trim(),attachments:old?.attachments||[],archived:false,createdAt:old?.createdAt||now,updatedAt:now});}
    if(!imported.length)throw new Error('No se encontraron filas válidas.');await idbBulkPut('orders',imported);const map=new Map(state.orders.map(o=>[o.id,o]));imported.forEach(o=>map.set(o.id,o));state.orders=[...map.values()];await audit('IMPORTACION',null,`Se importaron ${imported.length} órdenes desde ${file.name}, hoja ${sheet.name}.`);toast(`${imported.length} órdenes importadas.`, 'success');await refreshAll();
  }catch(err){console.error(err);toast(`No se pudo importar: ${err.message}`,'error',7000)}
}
function nextImportOt(imported){return `IMP-${todayISO().replaceAll('-','')}-${String(imported.length+1).padStart(4,'0')}`}
function exportRows(rows,filename){if(typeof XLSX!=='undefined'){const ws=XLSX.utils.json_to_sheet(rows);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Datos');XLSX.writeFile(wb,`${filename}.xlsx`)}else{const keys=Object.keys(rows[0]||{});const csv=[keys.join(';'),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(';'))].join('\n');downloadBlob(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),`${filename}.csv`)}}
function exportExcel(){const rows=getFilteredOrders(true).map(o=>({'OT':o.ot,'Fecha de aviso':o.date,'Fecha objetivo':o.dueDate,'Sala / Sector':o.sector,'Código activo':o.assetCode,'Equipo':o.equipment,'Solicitante':o.requester,'Tipo de Solicitud':o.type,'Aviso / Solicitud':o.description,'CRITICIDAD':o.criticality,'ESTADO':o.status,'Supervisor':o.supervisor,'Ejecutor':o.executor,'Horas planificadas':o.plannedHours,'Horas reales':o.actualHours,'Fecha de Finalización':o.completionDate,'OBS.':o.comments,'Archivada':o.archived?'Sí':'No'}));if(!rows.length){toast('No hay datos para exportar.','error');return}exportRows(rows,`ot_mtto_${todayISO()}`);audit('EXPORTACION',null,`Se exportaron ${rows.length} órdenes.`)}

function exportCSV(){
  const rows=getFilteredOrders(true).map(o=>({'OT':o.ot,'Fecha de aviso':o.date,'Fecha objetivo':o.dueDate,'Sala / Sector':o.sector,'Código activo':o.assetCode,'Equipo':o.equipment,'Solicitante':o.requester,'Tipo de Solicitud':o.type,'Aviso / Solicitud':o.description,'CRITICIDAD':o.criticality,'ESTADO':o.status,'Supervisor':o.supervisor,'Ejecutor':o.executor,'Horas planificadas':o.plannedHours,'Horas reales':o.actualHours,'Fecha de Finalización':o.completionDate,'OBS.':o.comments,'Archivada':o.archived?'Sí':'No'}));
  if(!rows.length){toast('No hay datos para exportar.','error');return}
  const keys=Object.keys(rows[0]);
  const csv=[keys.join(';'),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(';'))].join('\n');
  downloadBlob(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),`ot_mtto_${todayISO()}.csv`);audit('EXPORTACION',null,`Se exportaron ${rows.length} órdenes a CSV.`);
}

function backupJSON(){const data={app:'OT-MTTO Gestión',version:APP_VERSION,exportedAt:new Date().toISOString(),settings:state.settings,orders:state.orders,audit:state.audit};downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),`respaldo_ot_mtto_${todayISO()}.json`);audit('RESPALDO',null,'Se descargó un respaldo completo JSON.')}
async function restoreBackup(file){if(!file)return;if(!canArchive()){toast('Solo un administrador puede restaurar respaldos.','error');return}try{const data=JSON.parse(await file.text());if(!Array.isArray(data.orders))throw new Error('Respaldo inválido');if(!confirm(`Se reemplazarán los datos actuales por ${data.orders.length} órdenes. ¿Continuar?`))return;await idbClear('orders');await idbClear('audit');await idbBulkPut('orders',data.orders);if(Array.isArray(data.audit))await idbBulkPut('audit',data.audit);state.orders=data.orders;state.audit=(data.audit||[]).sort((a,b)=>b.ts.localeCompare(a.ts));state.settings={...DEFAULT_SETTINGS,...data.settings,id:'app'};await idbPut('settings',state.settings);await audit('RESTAURACION',null,`Se restauró el respaldo ${file.name}.`);applySettingsToUI();toast('Respaldo restaurado.','success');refreshAll()}catch(err){toast(`No se pudo restaurar: ${err.message}`,'error')}}
async function loadDemoData(){if(!canArchive())return;if(!confirm('¿Agregar los datos de demostración?'))return;const demo=demoOrders();await idbBulkPut('orders',demo);state.orders.push(...demo);await audit('DATOS_DEMO',null,`Se agregaron ${demo.length} órdenes de demostración.`);toast('Datos de demostración cargados.','success');refreshAll()}
async function clearAllData(){if(!canArchive())return;if(!confirm('Esta acción vaciará todas las órdenes y el historial local. Descargue antes un respaldo. ¿Continuar?'))return;await idbClear('orders');await idbClear('audit');state.orders=[];state.audit=[];state.settings.seeded=true;await idbPut('settings',state.settings);await audit('VACIADO',null,'Se vació la aplicación.');toast('Aplicación vaciada.','success');refreshAll()}

async function requestNotifications(){if(!('Notification'in window)){toast('Este navegador no admite notificaciones.','error');return}const perm=await Notification.requestPermission();if(perm==='granted'){toast('Notificaciones activadas.','success');sendMaintenanceNotification()}else toast('No se concedió permiso para notificaciones.','error')}
function sendMaintenanceNotification(){if(Notification.permission!=='granted')return;const urgent=state.orders.filter(o=>!o.archived&&!isClosed(o)&&norm(o.criticality)==='A');const overdue=state.orders.filter(o=>!o.archived&&isOverdue(o));if(urgent.length||overdue.length)new Notification('OT-MTTO Gestión',{body:`${urgent.length} urgentes abiertas · ${overdue.length} vencidas`,icon:'icon.svg'});}
function registerPWA(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.error)}
async function installApp(){if(!state.deferredInstallPrompt)return;state.deferredInstallPrompt.prompt();await state.deferredInstallPrompt.userChoice;state.deferredInstallPrompt=null;$('installBtn').classList.add('hidden')}

window.addEventListener('online',()=>{$('syncDot').style.background='#22c55e';toast('Conexión restablecida.','success')});window.addEventListener('offline',()=>{$('syncDot').style.background='#f59e0b';toast('Modo sin conexión: los datos locales siguen disponibles.')});
